name: Deploy

on: 
  release:
    types: [ created ]

jobs:
  deploy: 
    runs-on: windows-latest

    needs: [test-windows, test-macos]

    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: "15.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}