name: Tests

on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-windows:
    runs-on: windows-latest

    strategy:
      matrix: 
        node-version: [15.x]
    
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test

  test-macos:
    runs-on: macos-latest

    strategy:
      matrix: 
        node-version: [15.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test